# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "./src" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "./src" # Location of package manifests
    schedule:
      interval: "daily"

  # Not sure how to have dependabot track a top level
  # directory, so adding each individual image here:
  - package-ecosystem: "docker"
    directory: "./docker/rabbitmq-operator"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "./docker/signal-cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "./docker/sqlite3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "./docker/uptime-kuma"
    schedule:
      interval: "daily"
