---
- name: Build Graphapp
  hosts: worker01.cluster
  tasks:
    - name: Ensure git
      ansible.builtin.apt:
        name: git
        state: latest
    - name: Copy src
      ansible.builtin.synchronize:
        src: /home/blong14/Developer/git/graft-api
        dest: /home/pi
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.venv"
    - name: Build graft-api
      command: "docker build -t blong14/graphapp:latest graft-api"
    - name: Ping container
      command: "docker run --rm blong14/graphapp:latest waitress-serve --help"
    - name: Push image
      command: "docker push blong14/graphapp"
