---
- name: Clone Graphapp
  hosts: worker01.cluster
  tasks:
    - name: Ensure git
      ansible.builtin.apt:
        name: git
        state: latest
    - name: Checkout graft-api
      ansible.builtin.git:
        repo: git@github.com:graftapp/graft-api.git
        dest: /home/pi/graft-api
        version: master