apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{- include "scrape.name" . | nindent 4 }}
  labels:
    {{- include "scrape.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity: # TODO: move values.yaml
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - worker-01
                    - worker-02
                    - worker-03
          containers: # TODO: move to values.yaml
          - name: scrape
            image: blong14/scrape:arm-latest
            imagePullPolicy: Always
            command:
            - "/go/bin/scrutiny"
            - "news"
          restartPolicy: OnFailure
