kind: ConfigMap
apiVersion: v1
metadata:
  name: flink-operator-config
  namespace: flink-operator
data:
  # this will need to be templatized
  config: |-
    operator:
      ingressUrlFormat: "{{$jobCluster}}.local"
    logger:
      level: 4
