apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{- include "ridesscan.name" . | nindent 4 }}
  labels:
    {{- include "ridesscan.labels" . | nindent 4 }}
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: k3s.io/hostname
                    operator: In
                    values:
                    - worker-01
                    - worker-02
                    - worker-03
          containers:
          - name: ridesscan
            image: blong14/cluster:latest
            imagePullPolicy: Always
            command:
            - "/go/bin/cluster"
            - "run"
            - "ridesscan"
            - "--host=cockroachdb-public"
            - "--port=26257"
            - "--user=admin"
            - "--runner=direct"
            - "movr"
          restartPolicy: OnFailure
